import type { Metadata } from 'next';
import { articles, images, navigation, teamMembers, vision } from '@/lib/content';
import { InnerCTA, InsightGrid, PageIntro } from '@/components/inner-pages';
import { Button, Reveal } from '@/components/ui';

export const metadata: Metadata = { title: 'About Us', description: 'Meet Chandrakant B. Ghanchi and learn about Ghanchi Investments, serving 1,200+ clients in India and abroad since 2009.', alternates: { canonical: '/about-us' } };
const values = [{ title: 'Trust & integrity', description: 'A personal relationship built around understanding your needs.' }, { title: 'Focus', description: 'Your goals, risk appetite and cash flow guide the conversation.' }, { title: 'Excellence', description: 'Customized solutions with implementation assistance.' }, { title: 'Consistency', description: 'Annual reviews and ongoing service as your circumstances change.' }];
export default function AboutPage() {
  const founder = teamMembers[0];
  return <main id="main" className="inner-page"><section className="inner-about-cover"><img src={images.hero} alt="" fetchPriority="high"/><div className="inner-about-intro"><PageIntro title="Your goals. Our commitment." description="Personalized financial planning, protection and investment support since 2009."/><div className="container"><Button href={`#${founder.id}`} dot>Meet your advisor</Button></div></div></section><section id={founder.id} className="container page-section inner-founder"><Reveal><img className="inner-founder-photo" src={founder.headshot} alt={founder.name} loading="lazy"/><div className="inner-founder-label"><strong>{founder.name}</strong><span>{founder.role}</span></div></Reveal><Reveal className="inner-founder-letter"><p className="inner-eyebrow">Our introduction</p><h2>Helping you achieve<br/>your financial goals.</h2><p>{founder.bio}</p><p>Our clients include HNIs, business owners, NRIs, entrepreneurs, software engineers, advocates, doctors, architects, CEOs and CFOs.</p><p>Our mission is to educate people about retirement planning, support planning for children’s futures and help adults understand adequate insurance protection.</p><span className="inner-founder-signature">{founder.name}</span><div className="inner-team-socials">{founder.socialLinks.map(link => <a href={link.url} key={link.url}>{link.label}</a>)}</div></Reveal></section><section className="inner-values-wrap"><div className="container page-section"><div className="inner-section-heading"><h2>What we value.</h2></div><div className="inner-values">{values.map((value, index) => <Reveal className="inner-value" key={value.title} delay={index * .05}><span>{String(index + 1).padStart(2, '0')}</span><h3>{value.title}</h3><p>{value.description}</p></Reveal>)}</div></div></section><section className="container inner-philosophy"><p className="inner-eyebrow">Our vision</p><h2>“{vision}”</h2><p>Financial decisions should be made in the context of your life, not in isolation.</p></section><section className="container inner-services-grid" aria-label="Explore Ghanchi Investments">{navigation[1].children?.slice(1).map(item => <a className="inner-service-card" href={item.href} key={item.href}><h2>{item.title}</h2><span className="inner-service-more">Explore →</span></a>)}</section><section className="container page-section"><div className="inner-section-heading"><h2>Learn with us.</h2></div><InsightGrid items={articles}/></section><InnerCTA/></main>;
}
