"use client";

import { useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowUpRight, Plus } from 'lucide-react';
import { accordionSpring, Person, Reveal } from './ui';
import { teamMembers } from '@/lib/content';

const questions: Record<string, { question: string; answer: string }[]> = {
  General: [
    { question: 'What exactly does Kora do?', answer: 'We help B2B companies between $2M and $50M in revenue grow faster and more predictably. That means diagnosing what is stalling your growth, building the strategy to fix it, and working alongside your team to execute. We are not an agency that runs campaigns. We are a growth partner that works on the systems, processes, and positioning that drive sustainable revenue.' },
    { question: 'What industries do you work with?', answer: 'We work across B2B industries including SaaS, professional services, fintech, and healthtech. The common thread is companies with a strong product that need help building a repeatable growth engine. Our frameworks are industry-agnostic but we tailor every engagement to your specific market dynamics, competitive landscape, and buyer behavior.' },
    { question: 'How is Kora different from a marketing agency?', answer: 'Agencies typically execute specific tactics like paid ads, SEO, or content production. We work upstream of that. We figure out why your growth has stalled, what the highest-leverage opportunities are, and build the strategy and systems to capture them. If you need an agency for execution after that, we can help you find the right one. But most of the time, the problem is not a lack of tactics. It is a lack of clarity on what to prioritize.' },
    { question: 'Who on our team would work with Kora?', answer: 'Typically the founder or CEO, plus whoever owns revenue — whether that is a VP of Sales, Head of Marketing, or a revenue leader. We integrate into your existing team, not around it. We attend your standups, work in your tools, and collaborate directly with the people responsible for execution. Most clients say it feels like adding a senior team member, not hiring an outside consultant.' },
  ],
  Pricing: [
    { question: 'What happens on the discovery call?', answer: 'It is a 30-minute conversation where we learn about your business, your current growth challenges, and where you want to be in the next 12 months. No pitch deck, no pressure. If we think we can help, we will walk you through what an engagement would look like. If we are not the right fit, we will tell you that too.' },
    { question: 'Is there a minimum commitment?', answer: 'The Growth Sprint is a fixed 8-week engagement with no renewal obligation. The Growth Partnership runs on a monthly retainer with a 3-month minimum to give both sides enough time to build momentum and see real results. After that, it is month to month. Custom engagements are scoped individually based on what makes sense for your situation.' },
    { question: 'Can I switch between tiers?', answer: 'Yes. Many clients start with a Growth Sprint to address an immediate challenge, then move into a Growth Partnership once they see the value of ongoing support. We will always recommend the structure that fits where you are right now, and adjust as your needs evolve.' },
    { question: 'Do you work with startups or established companies?', answer: 'Both, but most of our clients are in the $2M to $50M revenue range. At that stage, the business has proven demand but needs a more structured approach to scale. If you are pre-revenue, we are probably not the right fit yet. If you are north of $50M, we can still help but the engagement is usually scoped as a Custom project.' },
    { question: 'What does the first week look like?', answer: 'We start with a deep dive into your data, your funnel, and your team. That means CRM access, analytics review, and conversations with key stakeholders. By the end of week one, you will have a diagnostic summary that identifies your biggest growth bottlenecks and a prioritized roadmap for what to tackle first. No fluff, no filler, just a clear picture of where the opportunities are.' },
  ],
  Process: [
    { question: 'How long before we start seeing results?', answer: 'Most clients see early signals within the first 30 days, things like improved pipeline velocity, clearer positioning, or higher conversion rates at specific funnel stages. Meaningful revenue impact typically shows up between 60 and 90 days. We set expectations honestly during the discovery call based on where your business is starting from.' },
    { question: 'How much time does this require from our team?', answer: 'We are designed to be low-friction. Expect 2 to 3 hours per week from your key stakeholders, mostly in the form of a weekly strategy sync and async collaboration in shared docs or Slack. We do the heavy lifting on research, analysis, and building deliverables. Your team’s time is focused on decision-making and execution, not busywork.' },
    { question: 'What tools or platforms do you work in?', answer: 'We work in your stack, not ours. That typically means your CRM, analytics platform, project management tool, and communication channels. We are experienced with HubSpot, Salesforce, Notion, Linear, Slack, and most of the common B2B tools. If you are using something niche, we will adapt. The point is to embed in your workflow, not create a parallel one.' },
    { question: 'What does a typical engagement look like week to week?', answer: 'After the initial diagnostic in week one, we move into a rhythm of weekly strategy sessions, async updates, and hands-on deliverables. Each week has a clear focus area tied to the roadmap. You will always know what we are working on, what is coming next, and how progress is tracking against the metrics we agreed on at kickoff.' },
  ],
  Results: [
    { question: 'What kind of results do your clients typically see?', answer: 'It varies by engagement, but common outcomes include 30 to 50 percent increases in pipeline velocity, 2 to 4x improvements in close rates, and measurable reductions in customer acquisition cost. Some clients have doubled revenue within 12 months. We share specific case studies during the discovery call so you can see what is realistic for a company at your stage.' },
    { question: 'Do you guarantee results?', answer: 'We do not make guarantees because growth depends on factors beyond any single engagement, including market conditions, team execution, and product strength. What we do guarantee is rigor, transparency, and accountability. We set measurable targets at the start of every engagement and report against them weekly. If something is not working, we pivot fast rather than running out the clock.' },
    { question: 'How do you measure success?', answer: 'We agree on specific KPIs during onboarding, typically a mix of leading indicators like pipeline growth and conversion rates, and lagging indicators like revenue and customer acquisition cost. We track these in a shared dashboard that updates weekly so both sides always know where things stand. No black boxes, no waiting until the end of the quarter for a report.' },
    { question: 'What happens after the engagement ends?', answer: 'You keep everything. Every playbook, process document, dashboard, and framework we build during the engagement belongs to you. We design our work to be self-sustaining so your team can continue executing without us. Many clients transition to a lighter advisory arrangement after the initial engagement, but it is entirely optional. The goal is always to leave you stronger than we found you.' },
  ],
};
export function FAQ() {
  const [category, setCategory] = useState('General');
  const [active, setActive] = useState<number | null>(0);
  const tabs = Object.keys(questions);
  return <section className="faq-section container section-space" id="faq"><Reveal><h2 className="display-title">FAQ</h2></Reveal><div className="faq-layout"><Reveal><div className="faq-tabs" role="tablist" aria-label="Frequently asked question categories" aria-orientation="vertical">{tabs.map((tab, i) => <button key={tab} id={`faq-tab-${tab}`} role="tab" aria-selected={category === tab} aria-controls="faq-panel" tabIndex={category === tab ? 0 : -1} onClick={() => { setCategory(tab); setActive(0); }} onKeyDown={event => { if (['ArrowDown', 'ArrowUp', 'ArrowLeft', 'ArrowRight'].includes(event.key)) { event.preventDefault(); const next = tabs[(i + (event.key === 'ArrowDown' || event.key === 'ArrowRight' ? 1 : 3)) % tabs.length]; setCategory(next); setActive(0); document.getElementById(`faq-tab-${next}`)?.focus(); } }}><span>{tab}</span><ArrowUpRight size={16}/></button>)}</div></Reveal><div id="faq-panel" role="tabpanel" aria-labelledby={`faq-tab-${category}`} className="faq-items">{questions[category].map((item, i) => <div className={`faq-item ${active === i ? 'open' : ''}`} key={`${category}-${item.question}`}><h3><button aria-expanded={active === i} aria-controls={`faq-answer-${category}-${i}`} onClick={() => setActive(active === i ? null : i)}>{item.question}<Plus size={22}/></button></h3><AnimatePresence initial={false}>{active === i && <motion.div id={`faq-answer-${category}-${i}`} initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} transition={accordionSpring}><p>{item.answer}</p></motion.div>}</AnimatePresence></div>)}<div className="faq-help"><Person image={teamMembers[4].headshot} name="More questions?" role="Reach out anytime."/><Link href="/contact">Let’s talk <ArrowUpRight size={17}/></Link></div></div></div></section>;
}
