import { chromium } from '@playwright/test';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
const data=JSON.parse(await readFile('reference/home.json','utf8'));
await mkdir('public/assets',{recursive:true});
const entries = [...new Map(data.images.slice(0,48).map((image,index)=>[new URL(image.src).pathname,{...image,index}])).values()];
await Promise.all(entries.map(async image=>{const url=new URL(image.src);url.searchParams.delete('scale-down-to');const res=await fetch(url);if(!res.ok)throw new Error(`Asset ${res.status}: ${url}`);await writeFile(`public/assets/${url.pathname.split('/').pop()}`,Buffer.from(await res.arrayBuffer()));}));
const font='https://framerusercontent.com/third-party-assets/fontshare/wf/6KNUAYMK3PTPQA22366IWF5JUVT35NZ3/E4CLT6PE4W64IV56BHAWFRZFLHPZIXFF/DEPNXL2T77QGX4DXZAN3G53TXHO2JEFP.woff2';
await writeFile('public/assets/manrope-variable.woff2',Buffer.from(await (await fetch(font)).arrayBuffer()));
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.goto('https://kora.framer.media/',{waitUntil:'networkidle'});
const svgs=await page.evaluate(()=>[...document.querySelectorAll('svg')].filter(el=>{const r=el.getBoundingClientRect();return r.width>60&&r.y<1000&&r.y>=0}).map(el=>{const copy=el.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');for(const use of copy.querySelectorAll('use')){const id=use.getAttribute('href')||use.getAttribute('xlink:href');const symbol=document.getElementById(id?.replace('#',''));if(symbol){const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.innerHTML=symbol.innerHTML;use.replaceWith(group);}}return {name:el.parentElement.dataset.framerName,svg:copy.outerHTML};}));
for(let i=0;i<svgs.length;i++)await writeFile(`public/assets/logo-${i}.svg`,svgs[i].svg);
console.log('Saved assets',entries.length,'logos',svgs.map((s,i)=>({i,name:s.name})));
await browser.close();
