import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto('http://localhost:3100/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
const loc = page.locator('.service-cta').first();
await loc.scrollIntoViewIfNeeded();
await page.waitForTimeout(1000);
const box = await loc.boundingBox();
console.log('box', box);
await page.screenshot({ path: 'reference/full-verify/shots-hover/debug-before.png', clip: { x: box.x - 20, y: box.y - 20, width: box.width + 40, height: box.height + 40 } });
const bgBefore = await loc.locator('a').evaluate(el => getComputedStyle(el).backgroundColor);
console.log('bg before', bgBefore);
await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
await page.waitForTimeout(600);
const bgAfter = await loc.locator('a').evaluate(el => getComputedStyle(el).backgroundColor);
console.log('bg after', bgAfter);
await page.screenshot({ path: 'reference/full-verify/shots-hover/debug-after.png', clip: { x: box.x - 20, y: box.y - 20, width: box.width + 40, height: box.height + 40 } });
await browser.close();
